version: 2
jobs:
  rust:
    docker:
      - image: circleci/rust:stretch
    environment:
      RUST_BACKTRACE: "1"
      RUSTFLAGS: "-Dwarnings"
    steps:
      - checkout
      - run: rustup component add clippy-preview rustfmt-preview
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all --tests -- -D clippy::all

workflows:
  version: 2
  ci-test:
      jobs:
        - rust
